"""
This module defines color palettes for different application themes.

Each theme is a dictionary of color values used for styling the application.
This centralized approach allows for easy theme management and customization.
"""

THEMES = {
    "Default Light": {
        "background": "#f8f9fa",
        "foreground": "#212529",
        "primary": "#007bff",
        "secondary": "#6c757d",
        "success": "#28a745",
        "danger": "#dc3545",
        "warning": "#ffc107",
        "info": "#17a2b8",
        "light": "#f8f9fa",
        "dark": "#343a40",
        "card_background": "#ffffff",
        "card_border": "#dee2e6",
        "text_muted": "#6c757d",
    },
    "Default Dark": {
        "background": "#212529",
        "foreground": "#f8f9fa",
        "primary": "#0d6efd",
        "secondary": "#6c757d",
        "success": "#198754",
        "danger": "#dc3545",
        "warning": "#ffc107",
        "info": "#0dcaf0",
        "light": "#f8f9fa",
        "dark": "#343a40",
        "card_background": "#343a40",
        "card_border": "#495057",
        "text_muted": "#adb5bd",
    },
    "Ocean Blue": {
        "background": "#e0f7fa",
        "foreground": "#004d40",
        "primary": "#00796b",
        "secondary": "#004d40",
        "success": "#2e7d32",
        "danger": "#c62828",
        "warning": "#ef6c00",
        "info": "#0277bd",
        "light": "#b2ebf2",
        "dark": "#004d40",
        "card_background": "#ffffff",
        "card_border": "#b2dfdb",
        "text_muted": "#455a64",
    },
    "Charcoal & Orange": {
        "background": "#36393f",
        "foreground": "#dcddde",
        "primary": "#fa8128",
        "secondary": "#72767d",
        "success": "#43b581",
        "danger": "#f04747",
        "warning": "#faa61a",
        "info": "#7289da",
        "light": "#b9bbbe",
        "dark": "#2f3136",
        "card_background": "#2f3136",
        "card_border": "#40444b",
        "text_muted": "#a3a6aa",
    },
    "Classic Professional": {
        "background": "#f4f4f4",
        "foreground": "#333333",
        "primary": "#2c3e50",
        "secondary": "#7f8c8d",
        "success": "#27ae60",
        "danger": "#c0392b",
        "warning": "#f39c12",
        "info": "#3498db",
        "light": "#ecf0f1",
        "dark": "#2c3e50",
        "card_background": "#ffffff",
        "card_border": "#bdc3c7",
        "text_muted": "#95a5a6",
    },
}
