"""initial

Revision ID: 374b7b0b9def
Revises: 
Create Date: 2025-05-28 09:49:53.938592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374b7b0b9def'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_length', sa.Float(), nullable=False),
    sa.Column('length_adder_per_inch', sa.Float(), nullable=True),
    sa.Column('length_adder_per_foot', sa.Float(), nullable=True),
    sa.Column('has_nonstandard_length_surcharge', sa.Boolean(), nullable=True),
    sa.Column('nonstandard_length_surcharge', sa.Float(), nullable=True),
    sa.Column('base_price_adder', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_code'), 'materials', ['code'], unique=True)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product_families', sa.String(), nullable=True),
    sa.Column('excluded_products', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_category'), 'options', ['category'], unique=False)
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.create_index(op.f('ix_options_name'), 'options', ['name'], unique=False)
    op.create_table('product_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_families_category'), 'product_families', ['category'], unique=False)
    op.create_index(op.f('ix_product_families_id'), 'product_families', ['id'], unique=False)
    op.create_index(op.f('ix_product_families_name'), 'product_families', ['name'], unique=False)
    op.create_table('standard_lengths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_lengths_id'), 'standard_lengths', ['id'], unique=False)
    op.create_index(op.f('ix_standard_lengths_material_code'), 'standard_lengths', ['material_code'], unique=False)
    op.create_table('cable_length_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_code'], ['materials.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_availability_id'), 'material_availability', ['id'], unique=False)
    op.create_index(op.f('ix_material_availability_material_code'), 'material_availability', ['material_code'], unique=False)
    op.create_index(op.f('ix_material_availability_product_type'), 'material_availability', ['product_type'], unique=False)
    op.create_table('material_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('o_ring_material_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('model_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('base_length', sa.Float(), nullable=True),
    sa.Column('voltage', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_model_number'), 'product_variants', ['model_number'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_category'), 'spare_parts', ['category'], unique=False)
    op.create_index(op.f('ix_spare_parts_id'), 'spare_parts', ['id'], unique=False)
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=False)
    op.create_table('voltage_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.String(), nullable=False),
    sa.Column('is_available', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('voltage', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_id'), 'quote_items', ['id'], unique=False)
    op.create_table('quote_item_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_item_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_item_options_id'), 'quote_item_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_item_options_id'), table_name='quote_item_options')
    op.drop_table('quote_item_options')
    op.drop_index(op.f('ix_quote_items_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_table('voltage_options')
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_category'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_product_variants_model_number'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_table('o_ring_material_options')
    op.drop_table('material_options')
    op.drop_index(op.f('ix_material_availability_product_type'), table_name='material_availability')
    op.drop_index(op.f('ix_material_availability_material_code'), table_name='material_availability')
    op.drop_index(op.f('ix_material_availability_id'), table_name='material_availability')
    op.drop_table('material_availability')
    op.drop_table('connection_options')
    op.drop_table('cable_length_options')
    op.drop_index(op.f('ix_standard_lengths_material_code'), table_name='standard_lengths')
    op.drop_index(op.f('ix_standard_lengths_id'), table_name='standard_lengths')
    op.drop_table('standard_lengths')
    op.drop_index(op.f('ix_product_families_name'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_id'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_category'), table_name='product_families')
    op.drop_table('product_families')
    op.drop_index(op.f('ix_options_name'), table_name='options')
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_index(op.f('ix_options_category'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_code'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
