"""Add choices, adders, rules to Option model

Revision ID: 3a7689ab8245
Revises: e181e14eae0d
Create Date: 2025-05-29 16:17:47.685445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7689ab8245'
down_revision: Union[str, None] = 'e181e14eae0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('choices', sa.JSON(), nullable=True))
    op.add_column('options', sa.Column('adders', sa.JSON(), nullable=True))
    op.add_column('options', sa.Column('rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'rules')
    op.drop_column('options', 'adders')
    op.drop_column('options', 'choices')
    # ### end Alembic commands ###
