"""add housing_type_option table

Revision ID: e181e14eae0d
Revises: 374b7b0b9def
Create Date: 2025-05-28 09:50:38.588510

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e181e14eae0d"
down_revision: Union[str, None] = "374b7b0b9def"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "housing_type_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_family_id", sa.Integer(), nullable=False),
        sa.Column("housing_type", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("is_available", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_family_id"],
            ["product_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("housing_type_options")
    # ### end Alembic commands ###
